In [ ]:
# biblioteca
import pandas as pd

In [ ]:
pd.__version__ # versão

'2.2.2'

In [ ]:
#previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
# classe
y = pd.read_csv('/content/saidas_breast.csv')
y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [ ]:
# biblioteca
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
sklearn.__version__ # versão

'1.6.1'

In [ ]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.25) # 25 % dos dados para testar e os 75% para treinar

In [ ]:
x_treinamento.shape, y_treinamento.shape # (registros)

((426, 30), (426, 1))

In [ ]:
x_teste.shape, y_teste.shape # (registros)

((143, 30), (143, 1))

In [ ]:
# biblioteca
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [ ]:
tf.__version__ # versão

'2.20.0'

In [ ]:
(30 + 1) / 2 # calculo de neuronios da camada oculta

15.5

In [ ]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'), # foi acrescentado depois
    tf.keras.layers.Dense(units = 1, activation= 'sigmoid')
]) # rede neural para duas camadas oculta

In [ ]:
30 * 16, 496 - 480 # Bias

(480, 16)

In [ ]:
496 + 17 # parametros totais

513

In [ ]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5) # Criando o otimizador

In [ ]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) # definindo os parametros

In [ ]:
426 / 10 # calculo do batch size

42.6

In [ ]:
rede_neural.fit(x_treinamento, y_treinamento, batch_size = 10, epochs = 100) # processamento

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5657 - loss: 1.3611
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7113 - loss: 0.6450
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7582 - loss: 0.5148
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7512 - loss: 0.7316
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.4008
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7535 - loss: 0.5007
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7441 - loss: 0.8310
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.4399
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 0.4063
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7770 - loss: 0.7261
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7700 - loss: 0.6313
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8216 - loss: 0.4623
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8146 - loss: 0.4443
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7441 - loss: 0.8896
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8638 - loss: 0.4297
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7512 - loss: 0.7849
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8192 - loss: 0.4645
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8380 - loss: 0.5021
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8310 - loss: 0.3983
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8662 - loss: 0.3894
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8568 - loss: 0.3505
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8732 - loss: 0.3107
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8451 - loss: 0.4119
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8263 - loss: 0.4741
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8146 - loss: 0.5089
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8662 - loss: 0.3348
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8146 - loss: 0.4801
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8756 - loss: 0.3440
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8709 - loss: 0.4027
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8451 - loss: 0.4714
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8427 - loss: 0.6576
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8005 - loss: 0.8033
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8169 - loss: 0.5686
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.4143
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7911 - loss: 0.6397
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8568 - loss: 0.3973
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8568 - loss: 0.4260
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.5057
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8333 - loss: 0.4661
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7793 - loss: 0.7562
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8380 - loss: 0.5064
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8099 - loss: 0.5408
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8146 - loss: 0.6852
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8380 - loss: 0.3978
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8192 - loss: 0.6031
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8099 - loss: 0.6081
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8545 - loss: 0.5055
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7911 - loss: 0.7681
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8498 - loss: 0.5354
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.4592
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7911 - loss: 1.2969
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8052 - loss: 0.7747
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8052 - loss: 0.5853
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8005 - loss: 0.5549
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8075 - loss: 0.6550
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8286 - loss: 0.5442
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8216 - loss: 0.6828
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7676 - loss: 0.8281
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.5286
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7629 - loss: 0.9125
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8052 - loss: 0.5832
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7700 - loss: 1.0069
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7629 - loss: 0.8138
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7840 - loss: 0.6826
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8122 - loss: 0.8650
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.6150
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8380 - loss: 1.0110
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8380 - loss: 0.4550
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.6930
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.5269
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8521 - loss: 0.5551
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8498 - loss: 0.5124
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7864 - loss: 0.7017
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8451 - loss: 0.5566
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8028 - loss: 0.7314
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.7730
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.5798
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8333 - loss: 0.5400
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8474 - loss: 0.4948
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8709 - loss: 0.4095
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.5413
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8451 - loss: 0.4779
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8192 - loss: 0.6123
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.4028
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 0.4620
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8521 - loss: 0.4180
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.9389
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8427 - loss: 0.6643
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.3990
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8099 - loss: 1.0320
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.6360
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8310 - loss: 0.5746
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7723 - loss: 1.1820
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.6206
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8028 - loss: 0.6338
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8192 - loss: 0.7381
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.6480
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8192 - loss: 0.5184
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7981 - loss: 0.9272
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8099 - loss: 0.7085

In [ ]:
x_teste

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
466,13.14,20.74,85.98,536.9,0.08675,0.10890,0.108500,0.035100,0.1562,0.06020,...,14.80,25.46,100.90,689.1,0.13510,0.35490,0.450400,0.118100,0.2563,0.08174
178,13.01,22.22,82.01,526.4,0.06251,0.01938,0.001595,0.001852,0.1395,0.05234,...,14.00,29.02,88.18,608.8,0.08125,0.03432,0.007977,0.009259,0.2295,0.05843
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,235.0000,0.07389,...,15.49,30.73,106.20,739.3,0.17030,0.54010,539.000000,206.000000,0.4378,0.10720
192,9.72,18.22,60.73,288.1,0.06950,0.02344,0.000000,0.000000,0.1653,0.06447,...,9968.00,20.83,62.25,303.8,0.07117,0.02729,0.000000,0.000000,0.1909,0.06559
227,15.00,15.51,97.45,684.5,0.08371,0.10960,0.065050,0.037800,0.1881,0.05907,...,16.41,19.31,114.20,808.2,0.11360,0.36270,0.340200,0.137900,0.2954,0.08362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,12.07,13.44,77.83,445.2,0.11000,0.09009,0.037810,0.027980,0.1657,0.06608,...,13.45,15.77,86.92,549.9,0.15210,0.16320,0.162200,0.073930,0.2781,0.08052
387,13.88,16.16,88.37,596.6,0.07026,0.04831,0.020450,0.008507,0.1607,0.05474,...,15.51,19.97,99.66,745.3,0.08484,0.12330,0.109100,0.045370,0.2542,0.06623
62,14.25,22.15,96.42,645.7,0.10490,0.20080,0.213500,0.086530,0.1949,0.07292,...,17.67,29.51,119.10,959.5,164.00000,0.62470,0.692200,0.178500,0.2844,0.11320
210,20.58,22.14,134.70,1290.0,0.09090,0.13480,164.000000,0.095610,0.1765,0.05024,...,23.24,27.84,158.30,1656.0,0.11780,292.00000,0.386100,192.000000,0.2909,0.05865
44,13.17,21.81,85.42,531.5,0.09714,0.10470,0.082590,0.052520,0.1746,0.06177,...,16.23,29.89,105.50,740.7,0.15030,0.39040,0.372800,0.160700,0.3693,0.09618

In [ ]:
pesos0 = rede_neural.layers[0].get_weights() # pesos da camada de entrada
pesos0

[array([[-3.08604807e-01, -3.75434682e-02, -4.80825305e-02,
         -5.83254918e-03, -2.83310950e-01,  4.21559773e-02,
         -1.34338886e-01,  1.55548856e-01,  3.07330549e-01,
         -4.89479691e-01, -1.03492402e-02, -8.87950230e-03,
          1.31174743e-01,  4.53588739e-02, -1.70881316e-01,
         -1.37943283e-01],
        [-3.72955084e-01, -6.94444701e-02, -6.83702156e-03,
          3.86419147e-02, -2.87078887e-01,  4.80894037e-02,
         -1.10905722e-01,  1.60220772e-01,  3.37799460e-01,
         -4.60955679e-01,  4.60562930e-02,  6.67046905e-02,
          1.84454367e-01,  5.27654700e-02, -2.96522379e-01,
         -3.20365205e-02],
        [-1.92496255e-01,  2.09088568e-02, -9.12423283e-02,
         -3.91594805e-02, -2.32207924e-01,  9.82415229e-02,
         -1.58943459e-02,  5.02562597e-02,  1.06277332e-01,
          3.73892859e-02, -3.65322977e-02, -7.89622217e-02,
          2.76937246e-01,  3.95947546e-02,  1.34325167e-02,
         -1.06769232e-02],
        [-1.00645125e-02,  3.29224728e-02,  1.07476741e-01,
          5.06613180e-02, -8.51079822e-02,  3.17284837e-02,
         -1.64655261e-02,  7.24469200e-02, -3.90400924e-02,
          2.11411938e-01,  4.08269502e-02, -9.79257189e-03,
          1.39332442e-02,  1.18802369e-01,  8.74289721e-02,
         -5.67110023e-03],
        [ 1.44715067e-02,  5.83505705e-02,  1.33143947e-01,
          1.34425759e-01, -2.30633661e-01,  1.10259354e-01,
          2.55703311e-02,  8.99048150e-02,  1.59877583e-01,
         -3.91415447e-01,  1.96993276e-01,  1.43229291e-01,
          2.21487153e-02,  1.32353781e-02, -2.97013402e-01,
          1.28533589e-02],
        [ 2.24443078e-02,  5.82790896e-02,  5.04135974e-02,
          1.27265975e-02,  7.84530416e-02, -3.46207246e-02,
          1.22031732e-03, -7.09073618e-02,  4.70666066e-02,
         -3.34262669e-01,  8.70940164e-02, -3.71637121e-02,
          5.07673696e-02,  3.98401059e-02, -1.04375310e-01,
         -1.09763108e-02],
        [-2.89379179e-01, -8.95796996e-03,  3.20263594e-01,
          1.37958407e-01, -2.36729071e-01, -8.54091644e-02,
          1.10933781e-02,  1.95065945e-01,  8.49551782e-02,
         -2.53054947e-01,  3.13646287e-01,  2.34428078e-01,
          1.81669742e-02, -1.00615211e-01, -3.35097134e-01,
         -3.46601754e-02],
        [-8.89690742e-02,  1.04974620e-01,  6.22963607e-02,
          4.32946533e-02,  4.43708748e-02, -7.37284049e-02,
         -1.32354093e-03, -1.12978637e-01, -5.77475466e-02,
         -7.14126229e-02,  8.40009227e-02,  4.96712998e-02,
          5.88822961e-02,  4.75580767e-02, -7.97098577e-02,
          5.83305359e-02],
        [ 1.34073511e-01, -6.70438260e-02, -2.56998185e-02,
         -2.25684389e-01,  2.48805881e-01, -4.45288211e-01,
         -5.81711493e-02, -5.67797162e-02, -1.04892686e-01,
          1.65180802e-01, -1.24551907e-01, -1.22011669e-01,
         -4.18781251e-01, -1.85818732e-01,  3.89430016e-01,
         -3.75973582e-02],
        [ 1.02702469e-01,  1.38521284e-01, -5.19160390e-01,
         -9.79519710e-02,  1.79717526e-01,  2.17571661e-01,
          5.42732626e-02, -2.68031389e-01, -1.00293875e-01,
          5.17627299e-01, -4.74234641e-01, -1.76737204e-01,
          9.77313370e-02, -8.08825046e-02,  3.81809980e-01,
          6.60513416e-02],
        [-4.30276066e-01,  2.51173414e-02,  3.68867861e-03,
         -2.94351969e-02, -9.18118283e-02, -1.48531765e-01,
         -1.76372118e-02, -3.32323462e-02,  7.21307620e-02,
          5.27826734e-02, -1.66977420e-01,  5.04176207e-02,
         -4.00117375e-02,  5.72242215e-02,  3.67182903e-02,
         -2.26999789e-01],
        [-8.46743360e-02,  6.88441247e-02, -1.08396031e-01,
         -3.97478007e-02,  1.03275590e-01,  9.31655169e-02,
          1.64312273e-02, -1.03995070e-01, -1.89698488e-02,
         -2.04654217e-01, -1.57152504e-01, -2.36041009e-01,
          2.56133126e-03, -2.76420675e-02,  2.15618029e-01,
         -3.12084681e-03],
        [ 1.03066824e-01,  1.06381878e-01,  8.35820064e-02,
         -2.55315960e-03, -9.03705880e-03,  2.86791548e-02,
         -1.55919623e-02,  1.05673037e-01,  3.78338806e-02,
          1.13704816e-01,  1.16183504e-01,  6.72204196e-02,
          2.88060773e-02,  1.85580075e-01,  4.58579510e-02,
          1.08715529e-02],
        [-9.59798872e-01,  1.82459757e-01,  2.37066627e-01,
          4.00841624e-01, -5.86050689e-01, -1.77882344e-01,
         -2.65358798e-02,  3.37149918e-01,  6.70519292e-01,
         -1.06477213e+00,  5.01623869e-01,  3.39761674e-01,
          3.26800607e-02,  1.59743041e-01, -9.16647673e-01,
         -2.69193321e-01],
        [-2.70722777e-01, -2.20636740e-01, -1.80573799e-02,
          3.02671473e-02, -3.43522727e-01,  1.65371411e-02,
         -2.87121199e-02,  8.70833099e-02,  1.31158948e-01,
          1.23208780e-02, -1.78504866e-02,  8.30119327e-02,
          2.53474414e-01, -1.60818487e-01, -2.42533833e-01,
         -2.50181369e-02],
        [-8.45425054e-02,  1.00286859e-04,  1.04626052e-01,
          6.35382682e-02, -5.32781519e-02, -2.79893458e-01,
         -1.26772091e-01,  1.35400876e-01,  4.37650979e-01,
         -6.46943212e-01,  1.69728026e-01,  4.71559130e-02,
         -1.41043290e-01,  3.32209691e-02, -1.13909438e-01,
         -1.63473308e-01],
        [-1.23734303e-01,  1.47593543e-01, -7.28495046e-02,
          6.39128673e-04,  2.57393658e-01,  9.12192613e-02,
          3.25618125e-02, -1.01223879e-01,  6.06356263e-02,
         -3.32774252e-01,  3.84080522e-02, -9.92451236e-02,
          7.87276030e-03,  2.23938957e-01,  1.37341708e-01,
         -5.03946468e-03],
        [ 5.34663051e-02,  1.32170051e-01, -3.74516189e-01,
         -1.74227562e-02,  2.48054877e-01,  2.70278811e-01,
          2.18776539e-02, -8.65791216e-02, -3.76874357e-02,
         -1.94849782e-02, -2.20872849e-01,  3.61128636e-02,
         -1.54376999e-01,  3.00409764e-01,  5.35415150e-02,
         -4.04552594e-02],
        [ 3.96563560e-01, -2.99347699e-01,  1.04625747e-01,
         -1.18740603e-01, -2.88219601e-01, -1.34053588e-01,
         -1.47396233e-02,  1.01401828e-01, -1.32668495e-01,
          7.11847484e-01,  4.18609008e-02, -1.56634688e-01,
          4.31667536e-01, -3.75375539e-01,  2.39191507e-03,
          2.29660973e-01],
        [-1.92319751e-01, -1.63666099e-01,  5.50895870e-01,
          6.46180958e-02, -1.92498147e-01, -3.20730537e-01,
         -4.99426499e-02,  3.92746896e-01,  1.55482501e-01,
         -4.63298082e-01,  5.59281886e-01,  2.18984798e-01,
         -1.08408883e-01, -1.66907147e-01, -3.51038218e-01,
         -9.78771821e-02],
        [-4.91950691e-01, -5.19986749e-02,  9.40513331e-03,
          4.54236604e-02, -2.88044602e-01, -7.59449378e-02,
          1.05692498e-01,  1.90617144e-01,  3.56849432e-01,
         -6.22278690e-01,  1.17550403e-01, -2.66020047e-03,
          5.04419021e-02,  1.58464164e-01, -3.01047772e-01,
         -1.70396134e-01],
        [-4.40299481e-01, -4.15684916e-02,  1.34873167e-01,
         -4.88981651e-03, -3.51679802e-01, -8.49049166e-02,
         -1.35664761e-01,  1.53048053e-01,  3.89805138e-01,
         -5.18033266e-01,  8.51850063e-02,  3.24913859e-02,
          1.55565336e-01, -2.28293613e-02, -3.48061472e-01,
         -6.52269796e-02],
        [-2.33967096e-01, -1.79921533e-03,  7.53521174e-02,
         -1.54689457e-02, -2.12972626e-01,  4.35212664e-02,
         -1.16226107e-01,  8.47267583e-02,  1.63373813e-01,
         -2.80716177e-02,  2.14546472e-02, -5.26403189e-02,
          2.26710856e-01,  1.39609158e-01, -8.18021819e-02,
         -1.72066484e-02],
        [-9.11162570e-02,  3.37507352e-02,  2.66789675e-01,
          6.21221922e-02, -6.10197186e-02, -4.48805764e-02,
         -2.26832181e-02,  1.66446656e-01,  3.42600122e-02,
          1.27622381e-01,  1.89041749e-01,  7.53196701e-02,
          4.19947021e-02,  1.40561640e-01, -7.75593594e-02,
         -6.52812198e-02],
        [-8.44341293e-02, -9.77374166e-02,  1.45120844e-01,
          1.37946792e-02, -1.95247889e-01,  2.82550231e-02,
         -3.88825163e-02,  3.91885303e-02,  5.57727627e-02,
          1.45357266e-01,  1.36091681e-02,  1.40497506e-01,
          5.07778861e-02, -1.46670386e-01, -2.62744546e-01,
          5.47900200e-02],
        [-4.29450460e-02, -4.93118726e-03,  2.76153743e-01,
          2.99585573e-02,  1.13448374e-01, -8.32335800e-02,
         -3.81221548e-02, -1.17591344e-01,  1.10643424e-01,
          1.45218745e-01,  1.10359699e-01,  1.08572885e-01,
         -8.95210449e-03,  4.31774110e-01, -1.37378671e-03,
         -5.55308945e-02],
        [ 3.32579874e-02,  7.69564882e-02, -2.68120114e-02,
         -3.91355269e-02,  5.96087724e-02,  1.92503616e-01,
          1.93102134e-03, -1.39628932e-01,  2.61454612e-01,
         -5.27826287e-02,  3.55411903e-03, -1.23717012e-02,
          8.60085860e-02,  2.46093154e-01, -2.68158223e-03,
          1.61547847e-02],
        [-1.92363843e-01, -1.24182336e-01,  2.91952819e-01,
          6.03244007e-02, -1.75926536e-01, -2.06266612e-01,
         -1.35582566e-01,  2.87073016e-01,  1.45136714e-01,
         -4.36481535e-01,  3.27675581e-01,  1.73903584e-01,
         -1.62826642e-01,  5.26178591e-02, -2.12244555e-01,
         -1.42176270e-01],
        [-2.89055735e-01, -4.78217006e-02,  1.28155559e-01,
         -8.39773857e-04, -2.25565284e-01,  4.46420573e-02,
         -7.03761280e-02, -5.53040355e-02,  8.44659805e-02,
         -7.57357255e-02,  2.41684467e-02,  8.31672028e-02,
          6.30117059e-02, -5.67562226e-03, -1.23590611e-01,
          2.79568974e-02],
        [-3.84996533e-01, -2.37615518e-02,  3.74089062e-01,
          1.77881137e-01, -3.08555096e-01, -2.53165007e-01,
         -3.48795913e-02,  3.02819401e-01,  2.33954743e-01,
         -4.13813651e-01,  3.66440773e-01,  3.11019272e-01,
         -7.45358095e-02, -5.55326566e-02, -5.02017796e-01,
         -1.37105808e-01]], dtype=float32),
 array([-0.04056205, -0.03493798, -0.44778234, -0.13860673, -0.11691134,
         0.31682485, -0.05050366, -0.1413421 ,  0.08903261,  0.01885869,
        -0.4759956 , -0.20239453,  0.33498052, -0.10038232,  0.12815781,
         0.05753956], dtype=float32)]

In [ ]:
len(pesos0) # quantidade de pesos

2

In [ ]:
len(pesos0[1])

16

In [ ]:
len(pesos0[0])

30

In [ ]:
pesos1 = rede_neural.layers[1].get_weights() # pesos da camada oculta
pesos1

[array([[-6.14234544e-02,  1.58725940e-02, -1.42249931e-03,
          3.52781313e-03,  5.54751009e-02, -3.38237062e-02,
          1.15486778e-01, -5.45807071e-02, -9.03424546e-02,
         -6.02095295e-03, -3.82355675e-02, -7.67848939e-02,
          2.33979262e-02, -5.73372617e-02, -2.64882166e-02,
         -3.53372050e-03],
        [-7.70112276e-02,  2.96810679e-02, -3.51449591e-03,
          3.19352038e-02,  9.32483189e-03,  3.77662457e-03,
         -5.95279224e-02,  9.11732689e-02,  3.10351141e-02,
         -8.61131921e-02,  3.58207300e-02, -6.52336702e-02,
         -5.25863515e-03, -2.93688346e-02, -5.52046746e-02,
          5.89531139e-02],
        [ 8.89401808e-02,  5.18943630e-02, -4.86278813e-03,
          1.21942073e-01,  2.42243949e-02,  3.36102815e-03,
         -2.39374191e-02,  6.59721345e-02, -3.26327933e-03,
          2.40596719e-02, -2.57432442e-02,  8.45527798e-02,
         -4.54519270e-03,  4.75485325e-02,  3.88599597e-02,
         -4.40599136e-02],
        [-5.81541173e-02, -9.16537493e-02,  4.36104909e-02,
         -2.85867732e-02, -4.92081009e-02,  2.56406404e-02,
         -6.36355355e-02,  8.20406303e-02, -1.54355578e-02,
         -2.89481357e-02, -3.39847021e-02, -1.43608436e-01,
         -1.40364571e-02, -7.87052587e-02, -4.61672433e-02,
          1.15968525e-01],
        [ 9.74429250e-02, -3.29207955e-03, -5.35627156e-02,
          1.12735003e-01,  2.76089441e-02,  4.17367648e-03,
          1.62669957e-01, -1.71978384e-01,  4.00221013e-02,
         -6.32888004e-02, -6.18858039e-02,  6.44290224e-02,
         -1.12245465e-02, -2.39865482e-02, -8.00360739e-02,
         -2.07028165e-03],
        [-2.57257074e-01, -1.83488578e-01, -8.41385722e-02,
          6.48882464e-02, -3.41611169e-02,  1.29772965e-02,
          2.99789757e-02,  2.62377203e-01, -1.98257696e-02,
         -1.70852110e-01,  1.64016839e-02, -2.43371263e-01,
         -7.27892593e-02, -1.13038637e-01, -3.34984958e-02,
          5.99724986e-02],
        [-4.28597219e-02, -1.23767950e-01, -4.06828243e-03,
          2.89682169e-02, -4.02491800e-02, -3.00974585e-02,
          5.46617322e-02,  9.95407850e-02, -7.33296052e-02,
         -4.75032739e-02, -4.02738638e-02, -6.59016594e-02,
         -2.96732876e-02, -3.82532850e-02, -3.10254376e-02,
          8.28188434e-02],
        [ 2.00034473e-02,  6.35709763e-02, -1.79070737e-02,
          1.12012878e-01, -2.86693349e-02, -3.77763696e-02,
         -1.79610122e-02, -1.54369667e-01,  3.14580202e-02,
          3.76612879e-02, -5.72819002e-02,  6.43451288e-02,
         -3.75660397e-02,  2.38794312e-02,  4.90895957e-02,
         -1.32438159e-02],
        [-2.20916241e-01, -4.20771509e-01, -1.03568174e-01,
          1.03969499e-01, -2.13317901e-01, -7.19541460e-02,
         -1.27546996e-01,  2.37147555e-01, -4.22835629e-03,
         -2.00394228e-01, -4.35172208e-02, -2.80290544e-01,
          6.91383984e-03, -1.05577566e-01, -4.07567918e-02,
          5.38393445e-02],
        [ 1.47091493e-01,  6.11193366e-02, -3.61804739e-02,
         -2.48626247e-02,  9.94730145e-02, -2.07709149e-03,
          1.80492565e-01, -1.49352446e-01,  1.50952926e-02,
          2.49667630e-01, -3.41416374e-02,  1.26039520e-01,
         -2.25985870e-02,  1.37145475e-01, -7.81145394e-02,
          1.40888035e-01],
        [ 4.95339558e-02, -2.22780494e-04,  2.35843677e-02,
          4.80269082e-02,  2.47221123e-02, -5.43101728e-02,
          9.53536190e-04, -1.50180247e-03,  4.88818660e-02,
          4.14855331e-02, -6.09294176e-02,  2.97304373e-02,
         -1.77751854e-03,  5.92543781e-02,  3.57473493e-02,
         -5.60429096e-02],
        [-9.50584114e-02, -7.46480376e-02, -3.02339811e-03,
         -1.40840895e-02, -7.12481365e-02,  2.36596502e-02,
          1.92256663e-02,  1.14580736e-01, -2.02171342e-03,
         -6.91289082e-03,  1.07730152e-02, -1.28736198e-01,
          3.38883847e-02, -5.16300015e-02, -5.53526171e-02,
          1.03359617e-01],
        [-3.27483773e-01, -4.10638183e-01,  3.58783603e-02,
         -2.10568439e-02, -1.46717280e-01, -5.83950244e-03,
         -1.86247543e-01,  2.36268401e-01, -3.29354942e-01,
         -8.33683386e-02, -5.10611683e-02, -3.15837562e-01,
         -5.52279241e-02, -8.04120302e-02, -1.00000404e-01,
         -1.87860280e-02],
        [-4.81582098e-02,  3.33928764e-02, -6.72309147e-03,
          3.91375385e-02,  1.58204418e-02, -1.51642384e-02,
         -5.86739974e-03,  7.01442286e-02,  4.17751521e-02,
         -2.19403580e-02, -2.43845247e-02, -3.85496113e-03,
         -3.19300778e-02, -5.08205295e-02, -8.55174754e-03,
          3.64999771e-02],
        [ 1.30288586e-01,  1.94157764e-01, -5.85803948e-02,
          6.32160064e-03,  1.10966370e-01, -3.09836213e-02,
          1.00866109e-01, -7.49589577e-02, -6.12572357e-02,
         -7.15692760e-03, -2.97947065e-03,  1.45581812e-01,
         -2.12282538e-02,  3.47231664e-02, -6.47847876e-02,
          4.41692472e-02],
        [-1.29766017e-01, -8.39782432e-02, -6.60467446e-02,
          1.12279572e-01,  7.85308704e-03, -2.42345594e-02,
          3.52089703e-02, -1.51037484e-01, -9.90643054e-02,
         -4.39980812e-03,  3.96274887e-02, -3.84798124e-02,
         -1.74279101e-02, -6.58613816e-02, -4.30997051e-02,
         -5.08467667e-02]], dtype=float32),
 array([ 0.09372129,  0.18135862, -0.1578657 , -0.3267518 ,  0.1429628 ,
        -0.00907033,  0.15857987,  0.38698938, -0.20865768,  0.09364109,
        -0.01367559,  0.14666276, -0.11517587,  0.10245303, -0.2966127 ,
         0.36555728], dtype=float32)]

In [ ]:
pesos2 = rede_neural.layers[2].get_weights() # pesos da camada oculta
pesos2

[array([[ 0.10561626],
        [ 0.14754725],
        [-0.63052094],
        [-0.22328536],
        [ 0.11032628],
        [-0.34376284],
        [ 0.15472522],
        [ 0.14547817],
        [-0.46976137],
        [ 0.21503893],
        [-0.12410948],
        [ 0.10507302],
        [-0.48283798],
        [ 0.05689038],
        [-0.281772  ],
        [ 0.17218693]], dtype=float32),
 array([0.30275223], dtype=float32)]

In [ ]:
previsoes = rede_neural.predict(x_teste) # celula da variavel de previsoes
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [ ]:
previsoes

array([[ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False]])

In [ ]:
y_teste

     0
466  1
178  1
8    0
192  1
227  1
..  ..
529  1
387  1
62   0
210  0
44   0

[143 rows x 1 columns]

In [ ]:
# importação
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
accuracy_score(y_teste, previsoes) # acuracia

0.8461538461538461

In [ ]:
confusion_matrix(y_teste, previsoes) # matriz de acertos por classes

array([[50,  7],
       [15, 71]])

In [ ]:
50 + 71, 15 + 7 # acertos, erros

(121, 22)

In [ ]:
121 / 143, 22 / 143 # taxa de acerto, erro

(0.8461538461538461, 0.15384615384615385)

In [ ]:
rede_neural.evaluate(x_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7483 - loss: 0.8892

[0.8891670107841492, 0.748251736164093]