In [2]:
# bibliotecas
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [3]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '2.0.2', '2.20.0', '1.6.1')

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [7]:
base = pd.read_csv('/content/iris.csv') # leitura do csv dos dados
base

     sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
X = base.iloc[:, 0:4] # todas as linhas e pegas as colunas 0,1,2 e 3
X

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
y = base.iloc[:, 4].values # mostras os valores das linhas apenas da coluna 4
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype=object)

In [10]:
label_encoder = LabelEncoder() # transforma as variaveis string em numeros(0,1,2)
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
np.shape(y) # quantidade

(150,)

In [13]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25) # separa os dados em treinamento e teste

In [14]:
X_treinamento.shape, X_teste.shape # quantidade de registros para treinamento e teste de X

((112, 4), (38, 4))

In [15]:
y_treinamento.shape, y_teste.shape # quantidade de registros para treinamento e teste de y

((112, 3), (38, 3))

In [17]:
(4 + 3) / 2 # quantidade de neuronios na camada oculta

3.5

In [18]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(input_shape=(4,)),
    tf.keras.layers.Dense(units=4, activation='relu'), # camada oculta
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax') # camada de saida, softmax pq tem o uso de mais de 2 classes
]) # rede neural onde cria uma sequencia de camada

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

In [21]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
rede_neural.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy']) # compilar a rede

In [23]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size=10, epochs=1000) # treinar a rede

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - categorical_accuracy: 0.3214 - loss: 1.3577
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3214 - loss: 1.2737
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3214 - loss: 1.1998
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3304 - loss: 1.1228
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5000 - loss: 1.0418
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6875 - loss: 0.9987
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5804 - loss: 0.9723
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.4375 - loss: 0.9533
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4018 - loss: 0.9452
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3929 - loss: 0.9373
Epoch 11/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.4554 - loss: 0.9283
Epoch 12/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6607 - loss: 0.9202
Epoch 13/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6339 - loss: 0.9121
Epoch 14/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6339 - loss: 0.9035
Epoch 15/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6518 - loss: 0.8950
Epoch 16/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6518 - loss: 0.8863
Epoch 17/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.6607 - loss: 0.8777
Epoch 18/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.6518 - loss: 0.8690
Epoch 19/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.6607 - loss: 0.8605
Epoch 20/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.6607 - loss: 0.8522
Epoch 21/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6518 - loss: 0.8435
Epoch 22/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6607 - loss: 0.8354
Epoch 23/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6607 - loss: 0.8275
Epoch 24/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.6696 - loss: 0.8197
Epoch 25/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6964 - loss: 0.8122
Epoch 26/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7143 - loss: 0.8059
Epoch 27/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7232 - loss: 0.7968
Epoch 28/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7143 - loss: 0.7897
Epoch 29/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7143 - loss: 0.7822
Epoch 30/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7411 - loss: 0.7754
Epoch 31/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7411 - loss: 0.7686
Epoch 32/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7321 - loss: 0.7618
Epoch 33/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7232 - loss: 0.7564
Epoch 34/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7411 - loss: 0.7497
Epoch 35/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7500 - loss: 0.7437
Epoch 36/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7500 - loss: 0.7378
Epoch 37/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7411 - loss: 0.7327
Epoch 38/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7679 - loss: 0.7267
Epoch 39/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7946 - loss: 0.7215
Epoch 40/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8036 - loss: 0.7163
Epoch 41/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8036 - loss: 0.7112
Epoch 42/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7768 - loss: 0.7069
Epoch 43/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7946 - loss: 0.7015
Epoch 44/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8036 - loss: 0.6965
Epoch 45/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8125 - loss: 0.6919
Epoch 46/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8036 - loss: 0.6874
Epoch 47/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7946 - loss: 0.6829
Epoch 48/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7946 - loss: 0.6787
Epoch 49/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7946 - loss: 0.6744
Epoch 50/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8036 - loss: 0.6708
Epoch 51/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8125 - loss: 0.6661
Epoch 52/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6620
Epoch 53/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.8304 - loss: 0.6580
Epoch 54/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6542
Epoch 55/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6502
Epoch 56/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6466
Epoch 57/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6429
Epoch 58/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8393 - loss: 0.6391
Epoch 59/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8393 - loss: 0.6358
Epoch 60/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8393 - loss: 0.6316
Epoch 61/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8393 - loss: 0.6285
Epoch 62/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8304 - loss: 0.6253
Epoch 63/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8393 - loss: 0.6213
Epoch 64/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8482 - loss: 0.6178
Epoch 65/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8482 - loss: 0.6146
Epoch 66/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8661 - loss: 0.6107
Epoch 67/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8571 - loss: 0.6074
Epoch 68/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.8393 - loss: 0.6042
Epoch 69/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8571 - loss: 0.6008
Epoch 70/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8571 - loss: 0.5978
Epoch 71/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8571 - loss: 0.5941
Epoch 72/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8661 - loss: 0.5909
Epoch 73/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8750 - loss: 0.5883
Epoch 74/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8839 - loss: 0.5843
Epoch 75/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8839 - loss: 0.5811
Epoch 76/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8839 - loss: 0.5776
Epoch 77/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8929 - loss: 0.5770
Epoch 78/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5721
Epoch 79/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8839 - loss: 0.5683
Epoch 80/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8929 - loss: 0.5653
Epoch 81/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9018 - loss: 0.5620
Epoch 82/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9107 - loss: 0.5583
Epoch 83/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8839 - loss: 0.5559
Epoch 84/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5531
Epoch 85/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5502
Epoch 86/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5459
Epoch 87/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.8929 - loss: 0.5439
Epoch 88/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9107 - loss: 0.5405
Epoch 89/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5382
Epoch 90/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9107 - loss: 0.5345
Epoch 91/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9196 - loss: 0.5311
Epoch 92/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5278
Epoch 93/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5250
Epoch 94/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9286 - loss: 0.5216
Epoch 95/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9286 - loss: 0.5198
Epoch 96/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5172
Epoch 97/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5135
Epoch 98/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5107
Epoch 99/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5078
Epoch 100/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.5040
Epoch 101/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.5022
Epoch 102/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4992
Epoch 103/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4952
Epoch 104/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4925
Epoch 105/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4899
Epoch 106/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4867
Epoch 107/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4846
Epoch 108/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4833
Epoch 109/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4788
Epoch 110/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4770
Epoch 111/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4734
Epoch 112/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4708
Epoch 113/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4680
Epoch 114/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4654
Epoch 115/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4626
Epoch 116/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4607
Epoch 117/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4579
Epoch 118/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4554
Epoch 119/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4524
Epoch 120/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4501
Epoch 121/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4542
Epoch 122/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4446
Epoch 123/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4446
Epoch 124/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4404
Epoch 125/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.4379
Epoch 126/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4357
Epoch 127/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4333
Epoch 128/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4311
Epoch 129/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.4297
Epoch 130/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.4265
Epoch 131/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.4273
Epoch 132/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4208
Epoch 133/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4220
Epoch 134/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4190
Epoch 135/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9375 - loss: 0.4156
Epoch 136/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4136
Epoch 137/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4110
Epoch 138/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4089
Epoch 139/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4064
Epoch 140/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9464 - loss: 0.4044
Epoch 141/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.4026
Epoch 142/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.4002
Epoch 143/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3981
Epoch 144/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.3983
Epoch 145/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3938
Epoch 146/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9554 - loss: 0.3928
Epoch 147/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3910
Epoch 148/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3886
Epoch 149/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3861
Epoch 150/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3834
Epoch 151/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3823
Epoch 152/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3805
Epoch 153/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3789
Epoch 154/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3776
Epoch 155/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3750
Epoch 156/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3728
Epoch 157/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3724
Epoch 158/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3674
Epoch 159/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3686
Epoch 160/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3653
Epoch 161/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3650
Epoch 162/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3615
Epoch 163/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3599
Epoch 164/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3584
Epoch 165/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3565
Epoch 166/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3565
Epoch 167/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3523
Epoch 168/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3530
Epoch 169/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3528
Epoch 170/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3479
Epoch 171/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3468
Epoch 172/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3478
Epoch 173/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3456
Epoch 174/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3415
Epoch 175/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9643 - loss: 0.3401
Epoch 176/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3383
Epoch 177/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3363
Epoch 178/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3345
Epoch 179/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3335
Epoch 180/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3316
Epoch 181/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.9732 - loss: 0.3301
Epoch 182/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3285
Epoch 183/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3280
Epoch 184/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3269
Epoch 185/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3254
Epoch 186/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3215
Epoch 187/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3210
Epoch 188/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3192
Epoch 189/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3170
Epoch 190/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3163
Epoch 191/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3180
Epoch 192/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3161
Epoch 193/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3124
Epoch 194/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3106
Epoch 195/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3092
Epoch 196/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3070
Epoch 197/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3065
Epoch 198/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3083
Epoch 199/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9732 - loss: 0.3063
Epoch 200/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9821 - loss: 0.3016
Epoch 201/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.9821 - loss: 0.3009

In [24]:
rede_neural.evaluate(X_teste, y_teste) # avaliar a rede

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - categorical_accuracy: 0.9474 - loss: 0.1692

[0.16918234527111053, 0.9473684430122375]

In [25]:
previsoes = rede_neural.predict(X_teste) # previsoes utilizando a variavel X_teste
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step

array([[3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [3.4940506e-03, 7.6799947e-01, 2.2850657e-01],
       [9.9999946e-01, 4.7842269e-07, 5.1851284e-20],
       [9.9999958e-01, 3.5169529e-07, 5.4901212e-20],
       [2.3408022e-03, 9.5748818e-01, 4.0170960e-02],
       [9.9999136e-01, 8.6285772e-06, 2.1887014e-16],
       [1.0327865e-04, 9.9989480e-01, 1.9432957e-06],
       [4.1679834e-04, 1.7348332e-02, 9.8223484e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [2.6754097e-03, 3.1199947e-01, 6.8532503e-01],
       [5.6332734e-04, 9.9902642e-01, 4.1028709e-04],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [8.8141547e-05, 9.9991065e-01, 1.1787794e-06],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [9.9999923e-01, 6.7259231e-07, 1.3401722e-19],
       [5.4586207e-04, 9.9908274e-01, 3.7144471e-04],
       [3.3554616e-03, 5.0916994e-01, 4.8747450e-01],
       [2.2172919e-03, 2.2399692e-01, 7.7378583e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [1.0910424e-03, 9.9558401e-01, 3.3249012e-03],
       [2.4284140e-04, 9.9972820e-01, 2.8828737e-05],
       [9.9999315e-01, 6.8514291e-06, 4.3015546e-17],
       [9.9999708e-01, 2.9156672e-06, 6.7257295e-18],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [9.9999827e-01, 1.6578836e-06, 1.6741492e-18],
       [2.2012282e-03, 2.2125980e-01, 7.7653891e-01],
       [9.9996561e-01, 3.4364901e-05, 1.1188329e-14],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [1.6579035e-03, 9.8562682e-01, 1.2715262e-02],
       [9.9999386e-01, 6.0558909e-06, 2.2909557e-16],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [9.9999249e-01, 7.5304597e-06, 1.1490710e-16],
       [9.9999988e-01, 1.6578427e-07, 3.6978209e-21],
       [9.9998736e-01, 1.2639281e-05, 3.3753580e-16],
       [9.9999785e-01, 2.1129752e-06, 1.6307010e-18],
       [9.9999905e-01, 9.4887696e-07, 1.5433061e-18]], dtype=float32)

In [26]:
previsoes = previsoes > 0.5 # facilitar o entendimento dos valores dividindo em True e False
print(previsoes)

[[False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]]

In [33]:
y_teste2 = [int(np.argmax(t)) for t in y_teste]
print(y_teste2) # representação no formato original das classes

[2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0]

In [34]:
previsoes2 = [int(np.argmax(t)) for t in previsoes]
print(previsoes2) # representação no formato original das classes

[2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 1, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0]

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_teste2, previsoes2) # acuracia do modelo

0.9473684210526315

In [40]:
# 0 setosa, 1 versicolor, 2 virginica

In [39]:
confusion_matrix(y_teste2, previsoes2)

array([[14,  0,  0],
       [ 0,  9,  1],
       [ 0,  1, 13]])