In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.82.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [2]:
# biblioteca
import pandas as pd
import tensorflow as tf
import sklearn

In [3]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Input
from tensorflow.keras.models import Model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
base = pd.read_csv('games.csv')
base

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# apagando alguns campos
base = base.drop('Other_Sales', axis = 1)
base = base.drop('Global_Sales', axis = 1)
base = base.drop('Developer', axis = 1)

In [6]:
base.shape

(16719, 13)

In [7]:
base.isnull().sum() # somatorio dos valores null de cada coluna

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Rating             6769
dtype: int64

In [8]:
base = base.dropna(axis = 0)

In [9]:
base.shape

(6825, 13)

In [10]:
base.isnull().sum() # somatorio dos valores null de cada coluna

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Rating             0
dtype: int64

In [11]:
base['Name'].value_counts() # contagem dos nomes diferentes

Name
Madden NFL 07                                   8
Need for Speed: Most Wanted                     8
LEGO Star Wars II: The Original Trilogy         8
Terraria                                        7
Madden NFL 08                                   7
                                               ..
Brain Age: Train Your Brain in Minutes a Day    1
Wii Fit                                         1
Wii Sports Resort                               1
Mario Kart Wii                                  1
Wii Sports                                      1
Name: count, Length: 4377, dtype: int64

In [12]:
base = base.drop('Name', axis = 1) # apagar os nomes

In [15]:
base.columns # para vizualizar a ordem

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [18]:
X = base.iloc[:, [0,1,2,3,7,8,9,10,11]].values
X # todos os atributos previsores

array([['Wii', 2006.0, 'Sports', ..., '8', 322.0, 'E'],
       ['Wii', 2008.0, 'Racing', ..., '8.3', 709.0, 'E'],
       ['Wii', 2009.0, 'Sports', ..., '8', 192.0, 'E'],
       ...,
       ['PC', 2014.0, 'Action', ..., '7.6', 412.0, 'M'],
       ['PC', 2011.0, 'Shooter', ..., '5.8', 43.0, 'T'],
       ['PC', 2011.0, 'Strategy', ..., '7.2', 13.0, 'E10+']], dtype=object)

In [19]:
y_na = base.iloc[:, 4].values
y_eu = base.iloc[:, 5].values
y_jp = base.iloc[:, 6].values
# variaveis dos locais na, eu, jp

In [20]:
y_na

array([4.136e+01, 1.568e+01, 1.561e+01, ..., 0.000e+00, 1.000e-02,
       0.000e+00])

In [21]:
y_eu

array([2.896e+01, 1.276e+01, 1.093e+01, ..., 1.000e-02, 0.000e+00,
       1.000e-02])

In [22]:
y_jp

array([3.77, 3.79, 3.28, ..., 0.  , 0.  , 0.  ])

In [24]:
# PS2 1 0 0 0 0 ...
# X360 0 1 0 0 ...
base['Platform'].value_counts() # contagem de plataformas

Platform
PS2     1140
X360     858
PS3      769
PC       651
XB       565
Wii      479
DS       464
PSP      390
GC       348
PS4      239
GBA      237
XOne     159
3DS      155
PS       150
PSV      118
WiiU      89
DC        14
Name: count, dtype: int64

In [25]:
base.columns

Index(['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Critic_Score', 'Critic_Count', 'User_Score',
       'User_Count', 'Rating'],
      dtype='object')

In [26]:
from numpy import remainder
onehotencoder = ColumnTransformer(transformers = [("OneHot", OneHotEncoder(), [0, 2, 3, 8])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X).toarray()

In [29]:
X.shape

(6825, 303)

In [30]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.006e+03, 7.600e+01,
       5.100e+01, 8.000e+00, 3.220e+02])

In [31]:
(303 + 3) / 2

153.0

In [32]:
camada_entrada = Input(shape = (303,))
camada_oculta1 = Dense(units = 153, activation='relu')(camada_entrada)
camada_oculta2 = Dense(units = 153, activation='relu')(camada_oculta1)
camada_saida1 = Dense(units = 1, activation='linear')(camada_oculta2)
camada_saida2 = Dense(units = 1, activation='linear')(camada_oculta2)
camada_saida3 = Dense(units = 1, activation='linear')(camada_oculta2)

In [33]:
regressor = Model(inputs = camada_entrada, outputs = [camada_saida1, camada_saida2, camada_saida3])

In [34]:
regressor.compile(optimizer='adam', loss = 'mse')

In [35]:
regressor.fit(X, [y_na, y_eu, y_jp], epochs=500, batch_size=100)

Epoch 1/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - dense_2_loss: 258.1945 - dense_3_loss: 1168.4600 - dense_4_loss: 52.7235 - loss: 1495.5490
Epoch 2/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - dense_2_loss: 6.2123 - dense_3_loss: 4.1818 - dense_4_loss: 3.4583 - loss: 13.6947
Epoch 3/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 3.4310 - dense_3_loss: 3.1846 - dense_4_loss: 4.3571 - loss: 11.0776
Epoch 4/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.6862 - dense_3_loss: 1.3479 - dense_4_loss: 0.7127 - loss: 3.7740
Epoch 5/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.3280 - dense_3_loss: 1.4180 - dense_4_loss: 2.2306 - loss: 6.0281
Epoch 6/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.4553 - dense_3_loss: 2.4834 - dense_4_loss: 0.5413 - loss: 5.3797
Epoch 7/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.8964 - dense_3_loss: 2.1327 - dense_4_loss: 5.4848 - loss: 10.6148
Epoch 8/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 3.2811 - dense_3_loss: 1.7148 - dense_4_loss: 47.2889 - loss: 52.8377
Epoch 9/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.3842 - dense_3_loss: 1.8394 - dense_4_loss: 0.4288 - loss: 4.6623
Epoch 10/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.6484 - dense_3_loss: 1.9311 - dense_4_loss: 1.4760 - loss: 6.0913
Epoch 11/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 10.5574 - dense_3_loss: 14.3516 - dense_4_loss: 1.0997 - loss: 26.2798
Epoch 12/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.6147 - dense_3_loss: 2.9148 - dense_4_loss: 1.4013 - loss: 6.9977
Epoch 13/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3810 - dense_3_loss: 2.3161 - dense_4_loss: 33.7741 - loss: 37.5880
Epoch 14/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.5844 - dense_3_loss: 0.8838 - dense_4_loss: 2.4025 - loss: 4.9081
Epoch 15/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0729 - dense_3_loss: 0.5926 - dense_4_loss: 0.7177 - loss: 2.4019
Epoch 16/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1302 - dense_3_loss: 0.5533 - dense_4_loss: 0.9897 - loss: 2.6934
Epoch 17/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9884 - dense_3_loss: 0.6381 - dense_4_loss: 0.1595 - loss: 1.7993
Epoch 18/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2890 - dense_3_loss: 0.9221 - dense_4_loss: 0.1418 - loss: 2.3664
Epoch 19/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.7756 - dense_3_loss: 2.1873 - dense_4_loss: 2.7830 - loss: 7.6105
Epoch 20/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 3.1514 - dense_3_loss: 2.4690 - dense_4_loss: 10.1740 - loss: 15.9433
Epoch 21/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9438 - dense_3_loss: 0.5111 - dense_4_loss: 0.4701 - loss: 1.9382
Epoch 22/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8795 - dense_3_loss: 0.4970 - dense_4_loss: 0.1599 - loss: 1.5431
Epoch 23/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9043 - dense_3_loss: 0.5073 - dense_4_loss: 0.3105 - loss: 1.7088
Epoch 24/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3410 - dense_3_loss: 0.9336 - dense_4_loss: 0.2450 - loss: 2.4619
Epoch 25/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 2.2724 - dense_3_loss: 1.7240 - dense_4_loss: 0.6518 - loss: 4.6285
Epoch 26/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.6062 - dense_3_loss: 1.1361 - dense_4_loss: 12.7793 - loss: 14.9124
Epoch 27/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.7417 - dense_3_loss: 2.4706 - dense_4_loss: 17.1415 - loss: 22.5889
Epoch 28/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0736 - dense_3_loss: 0.6904 - dense_4_loss: 0.2287 - loss: 2.0085
Epoch 29/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.3192 - dense_3_loss: 0.8942 - dense_4_loss: 0.1539 - loss: 2.3863
Epoch 30/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2278 - dense_3_loss: 0.6494 - dense_4_loss: 0.2138 - loss: 2.1047
Epoch 31/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9750 - dense_3_loss: 0.5152 - dense_4_loss: 0.1305 - loss: 1.6331
Epoch 32/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 1.0340 - dense_3_loss: 0.6223 - dense_4_loss: 0.1300 - loss: 1.7901
Epoch 33/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 2.1530 - dense_3_loss: 0.7162 - dense_4_loss: 0.2616 - loss: 3.1489
Epoch 34/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.1299 - dense_3_loss: 0.6996 - dense_4_loss: 0.2313 - loss: 2.0808
Epoch 35/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0871 - dense_3_loss: 0.9616 - dense_4_loss: 0.3432 - loss: 2.4101
Epoch 36/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.2456 - dense_3_loss: 1.0002 - dense_4_loss: 0.3395 - loss: 2.5642
Epoch 37/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.4022 - dense_3_loss: 1.0990 - dense_4_loss: 1.2916 - loss: 3.8265
Epoch 38/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1772 - dense_3_loss: 0.5594 - dense_4_loss: 1.7508 - loss: 3.5169
Epoch 39/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 4.6138 - dense_3_loss: 4.3822 - dense_4_loss: 1.4754 - loss: 10.4901
Epoch 40/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 8.1888 - dense_3_loss: 9.8557 - dense_4_loss: 1.6461 - loss: 19.7948
Epoch 41/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1030 - dense_3_loss: 0.9380 - dense_4_loss: 1.2777 - loss: 3.3459
Epoch 42/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - dense_2_loss: 0.9045 - dense_3_loss: 0.6451 - dense_4_loss: 0.4418 - loss: 2.0035
Epoch 43/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0789 - dense_3_loss: 0.6961 - dense_4_loss: 0.4991 - loss: 2.2908
Epoch 44/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8237 - dense_3_loss: 0.5035 - dense_4_loss: 1.0107 - loss: 2.3381
Epoch 45/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9516 - dense_3_loss: 0.6064 - dense_4_loss: 2.5788 - loss: 4.1231
Epoch 46/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.2242 - dense_3_loss: 0.6532 - dense_4_loss: 0.5748 - loss: 2.4632
Epoch 47/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9073 - dense_3_loss: 0.5994 - dense_4_loss: 0.6797 - loss: 2.2010
Epoch 48/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.3299 - dense_3_loss: 0.5226 - dense_4_loss: 0.7321 - loss: 2.5832
Epoch 49/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.3824 - dense_3_loss: 0.7272 - dense_4_loss: 0.2713 - loss: 2.4033
Epoch 50/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0031 - dense_3_loss: 0.5855 - dense_4_loss: 3.4139 - loss: 5.0118
Epoch 51/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0141 - dense_3_loss: 0.8892 - dense_4_loss: 2.4361 - loss: 4.2763
Epoch 52/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0624 - dense_3_loss: 0.9659 - dense_4_loss: 3.2301 - loss: 5.2598
Epoch 53/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1595 - dense_3_loss: 0.7738 - dense_4_loss: 2.4021 - loss: 4.3754
Epoch 54/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.2303 - dense_3_loss: 0.8266 - dense_4_loss: 0.1995 - loss: 2.2567
Epoch 55/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0902 - dense_3_loss: 0.5343 - dense_4_loss: 0.3662 - loss: 2.0048
Epoch 56/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9834 - dense_3_loss: 0.9109 - dense_4_loss: 0.2909 - loss: 2.2009
Epoch 57/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.7306 - dense_3_loss: 0.6963 - dense_4_loss: 0.4873 - loss: 2.9298
Epoch 58/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1568 - dense_3_loss: 0.4964 - dense_4_loss: 0.9966 - loss: 2.6706
Epoch 59/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0556 - dense_3_loss: 0.4936 - dense_4_loss: 0.6271 - loss: 2.1855
Epoch 60/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1863 - dense_3_loss: 0.8746 - dense_4_loss: 2.5662 - loss: 4.6681
Epoch 61/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1246 - dense_3_loss: 1.2309 - dense_4_loss: 2.0108 - loss: 4.3851
Epoch 62/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1340 - dense_3_loss: 2.7958 - dense_4_loss: 1.5509 - loss: 5.5188
Epoch 63/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.3622 - dense_3_loss: 1.3266 - dense_4_loss: 0.8936 - loss: 3.5735
Epoch 64/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.4047 - dense_3_loss: 1.0786 - dense_4_loss: 1.4186 - loss: 3.8856
Epoch 65/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 2.8971 - dense_3_loss: 1.4540 - dense_4_loss: 11.6796 - loss: 16.0487
Epoch 66/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.9620 - dense_3_loss: 0.7740 - dense_4_loss: 1.3360 - loss: 3.0983
Epoch 67/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.9533 - dense_3_loss: 0.6959 - dense_4_loss: 0.3419 - loss: 1.9415
Epoch 68/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0058 - dense_3_loss: 0.6823 - dense_4_loss: 0.3121 - loss: 1.9630
Epoch 69/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.3407 - dense_3_loss: 2.2129 - dense_4_loss: 0.8688 - loss: 4.4140
Epoch 70/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.2481 - dense_3_loss: 0.8069 - dense_4_loss: 0.3614 - loss: 2.4157
Epoch 71/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0376 - dense_3_loss: 0.7433 - dense_4_loss: 0.2355 - loss: 2.0316
Epoch 72/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9053 - dense_3_loss: 0.7265 - dense_4_loss: 0.1772 - loss: 1.8163
Epoch 73/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8684 - dense_3_loss: 0.6763 - dense_4_loss: 0.3151 - loss: 1.8298
Epoch 74/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.4742 - dense_3_loss: 1.2592 - dense_4_loss: 1.7980 - loss: 4.5763
Epoch 75/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - dense_2_loss: 1.0613 - dense_3_loss: 0.9943 - dense_4_loss: 0.4839 - loss: 2.5560
Epoch 76/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1235 - dense_3_loss: 0.9331 - dense_4_loss: 0.5816 - loss: 2.6518
Epoch 77/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1848 - dense_3_loss: 0.9430 - dense_4_loss: 1.1890 - loss: 3.3194
Epoch 78/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 0.9819 - dense_3_loss: 1.1561 - dense_4_loss: 0.6187 - loss: 2.7317
Epoch 79/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0153 - dense_3_loss: 0.9428 - dense_4_loss: 0.6241 - loss: 2.5341
Epoch 80/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - dense_2_loss: 1.0004 - dense_3_loss: 0.7474 - dense_4_loss: 0.5532 - loss: 2.3102
Epoch 81/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9884 - dense_3_loss: 0.7240 - dense_4_loss: 1.9714 - loss: 3.7032
Epoch 82/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9490 - dense_3_loss: 1.0033 - dense_4_loss: 0.8312 - loss: 2.7769
Epoch 83/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.9858 - dense_3_loss: 0.8200 - dense_4_loss: 1.1841 - loss: 2.9705
Epoch 84/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.7984 - dense_3_loss: 2.1367 - dense_4_loss: 7.5452 - loss: 11.5922
Epoch 85/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.2477 - dense_3_loss: 0.8491 - dense_4_loss: 0.8562 - loss: 2.9679
Epoch 86/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0172 - dense_3_loss: 1.1154 - dense_4_loss: 0.4634 - loss: 2.6102
Epoch 87/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1547 - dense_3_loss: 0.6774 - dense_4_loss: 0.5520 - loss: 2.4021
Epoch 88/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8771 - dense_3_loss: 0.7610 - dense_4_loss: 0.2766 - loss: 1.9149
Epoch 89/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 3.1372 - dense_3_loss: 2.9153 - dense_4_loss: 3.8165 - loss: 9.9467
Epoch 90/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.7936 - dense_3_loss: 0.6165 - dense_4_loss: 0.2025 - loss: 1.6273
Epoch 91/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9623 - dense_3_loss: 1.1586 - dense_4_loss: 0.1374 - loss: 2.2770
Epoch 92/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8373 - dense_3_loss: 0.7746 - dense_4_loss: 0.1947 - loss: 1.8220
Epoch 93/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8035 - dense_3_loss: 0.5773 - dense_4_loss: 0.1204 - loss: 1.5144
Epoch 94/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 1.1472 - dense_3_loss: 0.7378 - dense_4_loss: 0.1171 - loss: 2.0035
Epoch 95/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0209 - dense_3_loss: 0.7298 - dense_4_loss: 0.1303 - loss: 1.8901
Epoch 96/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.3846 - dense_3_loss: 0.8694 - dense_4_loss: 0.2385 - loss: 2.5049
Epoch 97/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0888 - dense_3_loss: 1.4676 - dense_4_loss: 0.1647 - loss: 2.7449
Epoch 98/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.9460 - dense_3_loss: 0.6981 - dense_4_loss: 0.1504 - loss: 1.7924
Epoch 99/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9692 - dense_3_loss: 0.9665 - dense_4_loss: 0.2275 - loss: 2.1556
Epoch 100/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8917 - dense_3_loss: 0.7935 - dense_4_loss: 0.2387 - loss: 1.9364
Epoch 101/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.1245 - dense_3_loss: 1.0235 - dense_4_loss: 0.3837 - loss: 2.5453
Epoch 102/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1606 - dense_3_loss: 1.0069 - dense_4_loss: 0.8483 - loss: 2.9956
Epoch 103/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.2025 - dense_3_loss: 1.9569 - dense_4_loss: 5.7885 - loss: 9.0134
Epoch 104/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9390 - dense_3_loss: 0.7769 - dense_4_loss: 0.2032 - loss: 1.9335
Epoch 105/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8313 - dense_3_loss: 0.7346 - dense_4_loss: 0.2540 - loss: 1.8337
Epoch 106/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8437 - dense_3_loss: 0.6039 - dense_4_loss: 0.2259 - loss: 1.6864
Epoch 107/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8396 - dense_3_loss: 0.5510 - dense_4_loss: 0.1931 - loss: 1.5700
Epoch 108/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9675 - dense_3_loss: 0.9749 - dense_4_loss: 0.3351 - loss: 2.2885
Epoch 109/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.8035 - dense_3_loss: 1.6402 - dense_4_loss: 3.0101 - loss: 6.5205
Epoch 110/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0537 - dense_3_loss: 1.2172 - dense_4_loss: 0.6855 - loss: 2.9783
Epoch 111/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9179 - dense_3_loss: 0.6605 - dense_4_loss: 0.1567 - loss: 1.7497
Epoch 112/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.1160 - dense_3_loss: 0.7809 - dense_4_loss: 0.1010 - loss: 2.0116
Epoch 113/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9429 - dense_3_loss: 0.8201 - dense_4_loss: 0.1656 - loss: 1.9411
Epoch 114/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8533 - dense_3_loss: 0.6389 - dense_4_loss: 0.1292 - loss: 1.6232
Epoch 115/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8471 - dense_3_loss: 0.7846 - dense_4_loss: 0.1571 - loss: 1.8009
Epoch 116/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8083 - dense_3_loss: 0.5605 - dense_4_loss: 0.1560 - loss: 1.5268
Epoch 117/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9192 - dense_3_loss: 0.9679 - dense_4_loss: 0.1222 - loss: 2.0205
Epoch 118/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9902 - dense_3_loss: 0.7274 - dense_4_loss: 0.2204 - loss: 1.9106
Epoch 119/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0448 - dense_3_loss: 0.8489 - dense_4_loss: 0.2794 - loss: 2.1897
Epoch 120/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0725 - dense_3_loss: 0.6884 - dense_4_loss: 0.2287 - loss: 1.9905
Epoch 121/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.9176 - dense_3_loss: 0.7358 - dense_4_loss: 0.1551 - loss: 1.8089
Epoch 122/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 0.8681 - dense_3_loss: 0.7709 - dense_4_loss: 0.2222 - loss: 1.8618
Epoch 123/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9381 - dense_3_loss: 0.8076 - dense_4_loss: 0.2505 - loss: 2.0000
Epoch 124/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_2_loss: 1.0251 - dense_3_loss: 0.7899 - dense_4_loss: 0.2638 - loss: 2.0790
Epoch 125/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9577 - dense_3_loss: 0.9890 - dense_4_loss: 0.3400 - loss: 2.3038
Epoch 126/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - dense_2_loss: 0.8628 - dense_3_loss: 0.6644 - dense_4_loss: 0.2511 - loss: 1.7783
Epoch 127/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.8607 - dense_3_loss: 0.5784 - dense_4_loss: 0.2404 - loss: 1.6919
Epoch 128/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9490 - dense_3_loss: 0.7857 - dense_4_loss: 0.2138 - loss: 1.9557
Epoch 129/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 0.9517 - dense_3_loss: 0.7613 - dense_4_loss: 0.4195 - loss: 2.1477
Epoch 130/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - dense_2_loss: 0.9758 - dense_3_loss: 0.7253 - dense_4_loss: 0.4341 - loss: 2.1124
Epoch 131/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - dense_2_loss: 1.0550 - dense_3_loss: 1.0027 - dense_4_loss: 1.0120 - loss: 3.0927
Epoch 132/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0232 - dense_3_loss: 0.7545 - dense_4_loss: 0.3054 - loss: 2.1012
Epoch 133/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9969 - dense_3_loss: 0.7237 - dense_4_loss: 0.2915 - loss: 2.0225
Epoch 134/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 0.9057 - dense_3_loss: 0.6718 - dense_4_loss: 0.1700 - loss: 1.7519
Epoch 135/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9418 - dense_3_loss: 0.5790 - dense_4_loss: 0.2579 - loss: 1.7909
Epoch 136/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9431 - dense_3_loss: 0.6781 - dense_4_loss: 0.2336 - loss: 1.8483
Epoch 137/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9011 - dense_3_loss: 0.5524 - dense_4_loss: 0.2703 - loss: 1.6567
Epoch 138/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8448 - dense_3_loss: 0.5270 - dense_4_loss: 0.3040 - loss: 1.6731
Epoch 139/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 1.0086 - dense_3_loss: 0.6535 - dense_4_loss: 0.6321 - loss: 2.3148
Epoch 140/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - dense_2_loss: 0.8701 - dense_3_loss: 0.6698 - dense_4_loss: 0.3481 - loss: 1.8913
Epoch 141/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8131 - dense_3_loss: 0.6149 - dense_4_loss: 0.4456 - loss: 1.8851
Epoch 142/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8297 - dense_3_loss: 0.4871 - dense_4_loss: 0.1706 - loss: 1.4667
Epoch 143/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.9314 - dense_3_loss: 0.5739 - dense_4_loss: 0.3255 - loss: 1.8424
Epoch 144/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - dense_2_loss: 0.8240 - dense_3_loss: 0.5588 - dense_4_loss: 0.3025 - loss: 1.6962
Epoch 145/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_2_loss: 0.8066 - dense_3_loss: 0.6588 - dense_4_loss: 0.2670 - loss: 1.7222
Epoch 146/500
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - dense_2_loss: 0.8330 - dense_3_loss: 0.6046 - dense_4_loss: 0.4002 - loss: 1.8521
Epoch 147/500

In [36]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(X) # Testando o modelo com os próprios dados de treinamento

214/214 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

In [37]:
previsao_na, previsao_na.mean() # previsao e media da previsao de na

(array([[15.514455  ],
        [11.859058  ],
        [12.649443  ],
        ...,
        [-0.2290887 ],
        [-0.12773108],
        [-0.12834409]], dtype=float32),
 np.float32(0.105369195))

In [38]:
y_na, y_na.mean() # valores de na, media da variavel de na

(array([4.136e+01, 1.568e+01, 1.561e+01, ..., 0.000e+00, 1.000e-02,
        0.000e+00]),
 np.float64(0.3944835164835165))

In [39]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_na, previsao_na) # erro medio absoluto

0.3170966082050687

In [40]:
previsao_eu, previsao_eu.mean() # previsao e media de eu

(array([[11.151625  ],
        [ 8.872805  ],
        [ 9.146378  ],
        ...,
        [ 0.01796886],
        [-0.04424992],
        [-0.02651668]], dtype=float32),
 np.float32(0.08532156))

In [42]:
y_eu, y_eu.mean() # valores de eu, media da variavel de eu

(array([2.896e+01, 1.276e+01, 1.093e+01, ..., 1.000e-02, 0.000e+00,
        1.000e-02]),
 np.float64(0.23608937728937732))

In [44]:
mean_absolute_error(y_eu, previsao_eu) # erro medio absoluto

0.188535821437137

In [45]:
previsao_jp, previsao_jp.mean() # previsao e media de jp

(array([[ 3.4030685 ],
        [ 3.8285487 ],
        [ 2.9532096 ],
        ...,
        [-0.07239521],
        [-0.03867896],
        [-0.02835295]], dtype=float32),
 np.float32(0.0072390637))

In [46]:
y_jp, y_jp.mean() # valores de jp, media da variavel de jp

(array([3.77, 3.79, 3.28, ..., 0.  , 0.  , 0.  ]),
 np.float64(0.06415824175824175))

In [48]:
mean_absolute_error(y_jp, previsao_jp) # erro medio absoluto

0.08210895480424056