In [2]:
# Manipulação de dados
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split # Divisão dos dados em treino e teste
from sklearn.preprocessing import StandardScaler # Normalização dos dados

# TensorFlow/Keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout

from sklearn.preprocessing import LabelEncoder # Transformação de Texto em Números

from sklearn.metrics import accuracy_score, mean_absolute_error # Métricas de avaliação

# Avaliação do modelo
from sklearn.metrics import accuracy_score, mean_absolute_error

In [3]:
df = pd.read_csv("/content/brasileirao.csv") # csv
df

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,ID,Rodada,Data,Casa,Fora,Gol_Casa,Gol_Fora,...,Posse_De_Bola_Casa,Posse_De_Bola_Fora,AtaquePerigoso_Casa,AtaquePerigoso_Fora,Ataque_Casa,Ataque_Fora,Finalizacao_Gol_Casa,Finalizacao_Gol_Fora,Finalizacao_Casa,Finalizacao_Fora
0,0,0.0,1.0,2024-24FlamengoBragantino,24,2024/08/25 20:00,Flamengo,Bragantino,2,1,...,50,50,73,75,110,104,7,2,6,9
1,1,1.0,2.0,2024-24InternacionalCruzeiro,24,2024/08/25 19:00,Internacional,Cruzeiro,1,0,...,44,56,54,26,126,84,9,3,10,2
2,2,2.0,3.0,2024-24São PauloVitória,24,2024/08/25 18:30,São Paulo,Vitória,2,1,...,58,42,39,34,81,77,3,4,9,6
3,3,3.0,4.0,2024-24EC BahiaBotafogo,24,2024/08/25 16:00,EC Bahia,Botafogo,0,0,...,53,47,47,38,83,84,7,3,10,9
4,4,4.0,5.0,2024-24Fortaleza ECCorinthians,24,2024/08/25 16:00,Fortaleza EC,Corinthians,1,0,...,45,55,32,34,89,84,5,2,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,605,605.0,606.0,2023-1PalmeirasCuiabá EC,1,2023/04/15 16:00,Palmeiras,Cuiabá EC,2,1,...,52,48,73,41,111,112,6,5,12,8
606,606,606.0,607.0,2023-1América MineiroFluminense,1,2023/04/15 16:00,América Mineiro,Fluminense,0,3,...,46,54,95,22,114,56,1,8,17,7
607,607,643.0,NaN,2024-24Vasco da GamaAthletico Paranaense,24,2024/08/26 21:00,Vasco da Gama,Athletico Paranaense,2,1,...,46,54,66,73,95,128,5,4,2,5
608,608,NaN,NaN,2024-19CriciúmaBragantino,19,2024/08/28 19:30,Criciúma,Bragantino,1,0,...,49,51,51,55,80,110,2,5,12,8
609,609,NaN,NaN,2024-5CruzeiroInternacional,5,2024/08/28 19:30,Cruzeiro,Internacional,0,0,...,68,32,78,26,109,70,4,0,16,1

In [4]:
df.shape # quantidade de linhas e colunas

(610, 27)

In [5]:
df.columns # nomes das colunas

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'ID', 'Rodada', 'Data',
       'Casa', 'Fora', 'Gol_Casa', 'Gol_Fora', 'Escanteios_Casa',
       'Escanteios_Fora', 'Cartao_Amarelo_Casa', 'Cartao_Amarelo_Fora',
       'Cartao_Vermelho_Casa', 'Cartao_Vermelho_Fora', 'PrimeiroGol',
       'Posse_De_Bola_Casa', 'Posse_De_Bola_Fora', 'AtaquePerigoso_Casa',
       'AtaquePerigoso_Fora', 'Ataque_Casa', 'Ataque_Fora',
       'Finalizacao_Gol_Casa', 'Finalizacao_Gol_Fora', 'Finalizacao_Casa',
       'Finalizacao_Fora'],
      dtype='object')

In [6]:
df.info() # informações gerais

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.2          610 non-null    int64
 1   Unnamed: 0.1          608 non-null    float64
 2   Unnamed: 0            607 non-null    float64
 3   ID                    610 non-null    object
 4   Rodada                610 non-null    int64
 5   Data                  610 non-null    object
 6   Casa                  610 non-null    object
 7   Fora                  610 non-null    object
 8   Gol_Casa              610 non-null    int64
 9   Gol_Fora              610 non-null    int64
 10  Escanteios_Casa       610 non-null    int64
 11  Escanteios_Fora       610 non-null    int64
 12  Cartao_Amarelo_Casa   610 non-null    int64
 13  Cartao_Amarelo_Fora   610 non-null    int64
 14  Cartao_Vermelho_Casa  610 non-null    int64
 15  Cartao_Vermelho_Fora  610 non-null    int64
 16  PrimeiroGol           566 non-null    object
 17  Posse_De_Bola_Casa    610 non-null    int64
 18  Posse_De_Bola_Fora    610 non-null    int64
 19  AtaquePerigoso_Casa   610 non-null    int64
 20  AtaquePerigoso_Fora   610 non-null    int64
 21  Ataque_Casa           610 non-null    int64
 22  Ataque_Fora           610 non-null    int64
 23  Finalizacao_Gol_Casa  610 non-null    int64
 24  Finalizacao_Gol_Fora  610 non-null    int64
 25  Finalizacao_Casa      610 non-null    int64
 26  Finalizacao_Fora      610 non-null    int64
dtypes: float64(2), int64(20), object(5)
memory usage: 128.8+ KB

In [7]:
# Remove colunas criadas automaticamente pelo Pandas
df.drop(columns=["Unnamed: 0","Unnamed: 0.1", "Unnamed: 0.2", "ID","Data"],inplace=True)

# Verifica o resultado
df.head()

,Rodada,Casa,Fora,Gol_Casa,Gol_Fora,Escanteios_Casa,Escanteios_Fora,Cartao_Amarelo_Casa,Cartao_Amarelo_Fora,Cartao_Vermelho_Casa,...,Posse_De_Bola_Casa,Posse_De_Bola_Fora,AtaquePerigoso_Casa,AtaquePerigoso_Fora,Ataque_Casa,Ataque_Fora,Finalizacao_Gol_Casa,Finalizacao_Gol_Fora,Finalizacao_Casa,Finalizacao_Fora
0,24,Flamengo,Bragantino,2,1,6,10,1,1,0,...,50,50,73,75,110,104,7,2,6,9
1,24,Internacional,Cruzeiro,1,0,12,3,2,2,0,...,44,56,54,26,126,84,9,3,10,2
2,24,São Paulo,Vitória,2,1,4,3,0,2,0,...,58,42,39,34,81,77,3,4,9,6
3,24,EC Bahia,Botafogo,0,0,4,7,4,4,0,...,53,47,47,38,83,84,7,3,10,9
4,24,Fortaleza EC,Corinthians,1,0,3,9,3,2,0,...,45,55,32,34,89,84,5,2,2,7

In [8]:
# Transformação de Texto em Números

encoder_casa = LabelEncoder()
encoder_fora = LabelEncoder()
encoder_primeiro = LabelEncoder()

df["Casa"] = encoder_casa.fit_transform(df["Casa"])
df["Fora"] = encoder_fora.fit_transform(df["Fora"])

# Trata valores nulos da coluna PrimeiroGol
df["PrimeiroGol"] = df["PrimeiroGol"].fillna("Nenhum")

df["PrimeiroGol"] = encoder_primeiro.fit_transform(df["PrimeiroGol"])

In [9]:
# 1 = vitória do mandante
# 0 = empate ou derrota
df["Vitoria"] = (df["Gol_Casa"] > df["Gol_Fora"]).astype(int) # criando coluna de vitoria
df[["Gol_Casa","Gol_Fora","Vitoria"]].head()

   Gol_Casa  Gol_Fora  Vitoria
0         2         1        1
1         1         0        1
2         2         1        1
3         0         0        0
4         1         0        1

In [10]:
# Definição das Entradas (X) e Saídas (y)
X = df.drop(columns=["Gol_Casa","Gol_Fora","Vitoria"]).values

y_class = df["Vitoria"].values

y_gols_casa = df["Gol_Casa"].values

y_gols_fora = df["Gol_Fora"].values

In [11]:
# treinamento de 80 % e 20 % de teste
X_train, X_test, y_c_train, y_c_test, y_gc_train, y_gc_test, y_gf_train, y_gf_test = train_test_split(X, y_class, y_gols_casa, y_gols_fora, test_size=0.2, random_state=42)

In [12]:
# Normalizando os Dados
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
input_layer = Input(shape=(X.shape[1],)) # Camada de entrada
shared = Dense(64, activation="relu")(input_layer) # Camadas ocultas compartilhadas

shared = Dropout(0.3)(shared)
shared = Dense(32, activation="relu")(shared)

out_class = Dense(1, activation="sigmoid", name="vitoria")(shared) # Saída de classificação

out_gols_casa = Dense(1, activation="linear", name="gols_casa")(shared) # Saída de regressão
out_gols_fora = Dense(1, activation="linear", name="gols_fora")(shared) # Saída de regressão

In [20]:
model = Model(inputs=input_layer,outputs=[out_class,out_gols_casa,out_gols_fora]) # montagem do modelo

In [22]:
model.compile(optimizer="adam", # compilacao de rede
    loss={
        "vitoria":"binary_crossentropy",
        "gols_casa":"mse",
        "gols_fora":"mse"
    },
    metrics={
        "vitoria":"accuracy",
        "gols_casa":"mae",
        "gols_fora":"mae"})

In [23]:
historico = model.fit(X_train,[y_c_train, y_gc_train, y_gf_train],epochs=50,batch_size=32,verbose=1) # treinamento do modelo

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - gols_casa_loss: 2.3789 - gols_casa_mae: 1.2363 - gols_fora_loss: 1.5787 - gols_fora_mae: 0.9340 - loss: 4.6969 - vitoria_accuracy: 0.5369 - vitoria_loss: 0.6884
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - gols_casa_loss: 1.5554 - gols_casa_mae: 0.9687 - gols_fora_loss: 1.2274 - gols_fora_mae: 0.8348 - loss: 3.4665 - vitoria_accuracy: 0.5533 - vitoria_loss: 0.6869
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 1.3191 - gols_casa_mae: 0.8954 - gols_fora_loss: 1.0804 - gols_fora_mae: 0.8140 - loss: 3.0929 - vitoria_accuracy: 0.5861 - vitoria_loss: 0.6754
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 1.2629 - gols_casa_mae: 0.8734 - gols_fora_loss: 1.0438 - gols_fora_mae: 0.7848 - loss: 3.0067 - vitoria_accuracy: 0.5758 - vitoria_loss: 0.6734
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 1.0685 - gols_casa_mae: 0.8261 - gols_fora_loss: 0.9171 - gols_fora_mae: 0.7483 - loss: 2.7064 - vitoria_accuracy: 0.5963 - vitoria_loss: 0.6729
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 1.0832 - gols_casa_mae: 0.8068 - gols_fora_loss: 0.8325 - gols_fora_mae: 0.7211 - loss: 2.5606 - vitoria_accuracy: 0.6291 - vitoria_loss: 0.6369
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - gols_casa_loss: 1.0784 - gols_casa_mae: 0.8082 - gols_fora_loss: 0.8759 - gols_fora_mae: 0.7173 - loss: 2.6041 - vitoria_accuracy: 0.6209 - vitoria_loss: 0.6447
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - gols_casa_loss: 1.0478 - gols_casa_mae: 0.7916 - gols_fora_loss: 0.8301 - gols_fora_mae: 0.7099 - loss: 2.5474 - vitoria_accuracy: 0.6332 - vitoria_loss: 0.6443
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.9789 - gols_casa_mae: 0.7760 - gols_fora_loss: 0.7313 - gols_fora_mae: 0.6862 - loss: 2.3849 - vitoria_accuracy: 0.6516 - vitoria_loss: 0.6523
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.9098 - gols_casa_mae: 0.7487 - gols_fora_loss: 0.7931 - gols_fora_mae: 0.7001 - loss: 2.3834 - vitoria_accuracy: 0.6639 - vitoria_loss: 0.6311
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - gols_casa_loss: 0.9064 - gols_casa_mae: 0.7256 - gols_fora_loss: 0.7882 - gols_fora_mae: 0.6884 - loss: 2.3174 - vitoria_accuracy: 0.6742 - vitoria_loss: 0.6228
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - gols_casa_loss: 0.8982 - gols_casa_mae: 0.7314 - gols_fora_loss: 0.7042 - gols_fora_mae: 0.6527 - loss: 2.2300 - vitoria_accuracy: 0.6967 - vitoria_loss: 0.6074
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.8198 - gols_casa_mae: 0.7087 - gols_fora_loss: 0.7326 - gols_fora_mae: 0.6735 - loss: 2.1627 - vitoria_accuracy: 0.6844 - vitoria_loss: 0.5955
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.9161 - gols_casa_mae: 0.7364 - gols_fora_loss: 0.7246 - gols_fora_mae: 0.6673 - loss: 2.2108 - vitoria_accuracy: 0.7111 - vitoria_loss: 0.5809
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - gols_casa_loss: 0.8729 - gols_casa_mae: 0.7394 - gols_fora_loss: 0.6669 - gols_fora_mae: 0.6466 - loss: 2.1532 - vitoria_accuracy: 0.6865 - vitoria_loss: 0.5879
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8799 - gols_casa_mae: 0.7371 - gols_fora_loss: 0.7363 - gols_fora_mae: 0.6526 - loss: 2.1625 - vitoria_accuracy: 0.7152 - vitoria_loss: 0.5849
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8313 - gols_casa_mae: 0.7130 - gols_fora_loss: 0.6650 - gols_fora_mae: 0.6446 - loss: 2.0843 - vitoria_accuracy: 0.6906 - vitoria_loss: 0.5796
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8498 - gols_casa_mae: 0.7348 - gols_fora_loss: 0.6813 - gols_fora_mae: 0.6263 - loss: 2.0606 - vitoria_accuracy: 0.7090 - vitoria_loss: 0.5698
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.7928 - gols_casa_mae: 0.6829 - gols_fora_loss: 0.7154 - gols_fora_mae: 0.6563 - loss: 2.1093 - vitoria_accuracy: 0.7049 - vitoria_loss: 0.5815
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8322 - gols_casa_mae: 0.7037 - gols_fora_loss: 0.6616 - gols_fora_mae: 0.6456 - loss: 2.0350 - vitoria_accuracy: 0.7008 - vitoria_loss: 0.5662
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.7769 - gols_casa_mae: 0.6964 - gols_fora_loss: 0.5956 - gols_fora_mae: 0.6053 - loss: 1.9307 - vitoria_accuracy: 0.7357 - vitoria_loss: 0.5388
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.7751 - gols_casa_mae: 0.6981 - gols_fora_loss: 0.6231 - gols_fora_mae: 0.6151 - loss: 1.9649 - vitoria_accuracy: 0.6967 - vitoria_loss: 0.5624
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8240 - gols_casa_mae: 0.7062 - gols_fora_loss: 0.6434 - gols_fora_mae: 0.6259 - loss: 1.9881 - vitoria_accuracy: 0.7234 - vitoria_loss: 0.5501
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.7985 - gols_casa_mae: 0.7071 - gols_fora_loss: 0.6420 - gols_fora_mae: 0.6064 - loss: 2.0071 - vitoria_accuracy: 0.7152 - vitoria_loss: 0.5538
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8307 - gols_casa_mae: 0.6844 - gols_fora_loss: 0.5832 - gols_fora_mae: 0.5950 - loss: 1.9256 - vitoria_accuracy: 0.6947 - vitoria_loss: 0.5541
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - gols_casa_loss: 0.8111 - gols_casa_mae: 0.7138 - gols_fora_loss: 0.6118 - gols_fora_mae: 0.6201 - loss: 2.0170 - vitoria_accuracy: 0.7029 - vitoria_loss: 0.5551
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - gols_casa_loss: 0.7709 - gols_casa_mae: 0.6921 - gols_fora_loss: 0.6238 - gols_fora_mae: 0.5901 - loss: 1.9129 - vitoria_accuracy: 0.7357 - vitoria_loss: 0.5307
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.7864 - gols_casa_mae: 0.6949 - gols_fora_loss: 0.6346 - gols_fora_mae: 0.6131 - loss: 1.9454 - vitoria_accuracy: 0.7295 - vitoria_loss: 0.5319
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - gols_casa_loss: 0.7658 - gols_casa_mae: 0.6671 - gols_fora_loss: 0.5806 - gols_fora_mae: 0.5998 - loss: 1.8776 - vitoria_accuracy: 0.7357 - vitoria_loss: 0.5264
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - gols_casa_loss: 0.7648 - gols_casa_mae: 0.6996 - gols_fora_loss: 0.6035 - gols_fora_mae: 0.6059 - loss: 1.9174 - vitoria_accuracy: 0.7316 - vitoria_loss: 0.5276
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - gols_casa_loss: 0.7478 - gols_casa_mae: 0.6707 - gols_fora_loss: 0.6264 - gols_fora_mae: 0.6109 - loss: 1.9177 - vitoria_accuracy: 0.7193 - vitoria_loss: 0.5550
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - gols_casa_loss: 0.6916 - gols_casa_mae: 0.6614 - gols_fora_loss: 0.5859 - gols_fora_mae: 0.6062 - loss: 1.8100 - vitoria_accuracy: 0.7500 - vitoria_loss: 0.5109
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - gols_casa_loss: 0.7208 - gols_casa_mae: 0.6668 - gols_fora_loss: 0.5910 - gols_fora_mae: 0.5952 - loss: 1.8606 - vitoria_accuracy: 0.7336 - vitoria_loss: 0.5303
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - gols_casa_loss: 0.7401 - gols_casa_mae: 0.6823 - gols_fora_loss: 0.5879 - gols_fora_mae: 0.6019 - loss: 1.8672 - vitoria_accuracy: 0.7316 - vitoria_loss: 0.5228
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - gols_casa_loss: 0.7418 - gols_casa_mae: 0.6598 - gols_fora_loss: 0.5897 - gols_fora_mae: 0.5907 - loss: 1.8003 - vitoria_accuracy: 0.7520 - vitoria_loss: 0.5278
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.7354 - gols_casa_mae: 0.6726 - gols_fora_loss: 0.5943 - gols_fora_mae: 0.6006 - loss: 1.8637 - vitoria_accuracy: 0.7439 - vitoria_loss: 0.5091
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - gols_casa_loss: 0.7171 - gols_casa_mae: 0.6779 - gols_fora_loss: 0.5789 - gols_fora_mae: 0.6042 - loss: 1.8409 - vitoria_accuracy: 0.7234 - vitoria_loss: 0.5133
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - gols_casa_loss: 0.7001 - gols_casa_mae: 0.6601 - gols_fora_loss: 0.5443 - gols_fora_mae: 0.5773 - loss: 1.7541 - vitoria_accuracy: 0.7377 - vitoria_loss: 0.4942
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - gols_casa_loss: 0.7638 - gols_casa_mae: 0.6756 - gols_fora_loss: 0.5564 - gols_fora_mae: 0.5765 - loss: 1.7817 - vitoria_accuracy: 0.7398 - vitoria_loss: 0.5011
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - gols_casa_loss: 0.7405 - gols_casa_mae: 0.6602 - gols_fora_loss: 0.6134 - gols_fora_mae: 0.6013 - loss: 1.8387 - vitoria_accuracy: 0.7316 - vitoria_loss: 0.5231
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.7019 - gols_casa_mae: 0.6552 - gols_fora_loss: 0.6079 - gols_fora_mae: 0.6114 - loss: 1.8577 - vitoria_accuracy: 0.7152 - vitoria_loss: 0.5062
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - gols_casa_loss: 0.7429 - gols_casa_mae: 0.6413 - gols_fora_loss: 0.5425 - gols_fora_mae: 0.5793 - loss: 1.7406 - vitoria_accuracy: 0.7316 - vitoria_loss: 0.4980
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.7089 - gols_casa_mae: 0.6585 - gols_fora_loss: 0.5479 - gols_fora_mae: 0.5779 - loss: 1.7415 - vitoria_accuracy: 0.7418 - vitoria_loss: 0.4890
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - gols_casa_loss: 0.7072 - gols_casa_mae: 0.6477 - gols_fora_loss: 0.5397 - gols_fora_mae: 0.5886 - loss: 1.7350 - vitoria_accuracy: 0.7377 - vitoria_loss: 0.5068
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - gols_casa_loss: 0.7104 - gols_casa_mae: 0.6503 - gols_fora_loss: 0.5247 - gols_fora_mae: 0.5770 - loss: 1.7563 - vitoria_accuracy: 0.7357 - vitoria_loss: 0.5239
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - gols_casa_loss: 0.6982 - gols_casa_mae: 0.6732 - gols_fora_loss: 0.5130 - gols_fora_mae: 0.5629 - loss: 1.7270 - vitoria_accuracy: 0.7418 - vitoria_loss: 0.4993
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - gols_casa_loss: 0.6859 - gols_casa_mae: 0.6479 - gols_fora_loss: 0.5488 - gols_fora_mae: 0.5726 - loss: 1.7451 - vitoria_accuracy: 0.7480 - vitoria_loss: 0.5072
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - gols_casa_loss: 0.6310 - gols_casa_mae: 0.6247 - gols_fora_loss: 0.5027 - gols_fora_mae: 0.5598 - loss: 1.6457 - vitoria_accuracy: 0.7336 - vitoria_loss: 0.4833
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - gols_casa_loss: 0.7208 - gols_casa_mae: 0.6555 - gols_fora_loss: 0.5266 - gols_fora_mae: 0.5691 - loss: 1.7407 - vitoria_accuracy: 0.7582 - vitoria_loss: 0.5092
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - gols_casa_loss: 0.7355 - gols_casa_mae: 0.6580 - gols_fora_loss: 0.5165 - gols_fora_mae: 0.5687 - loss: 1.7319 - vitoria_accuracy: 0.7336 - vitoria_loss: 0.4981

In [24]:
previsoes = model.predict(X_test) # previsoes

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

In [26]:
#Avaliacao de classificação
vitoria_pred = (previsoes[0] > 0.5).astype(int)

acuracia = accuracy_score(y_c_test, vitoria_pred)
print("Acurácia:", acuracia)

Acurácia: 0.6557377049180327

In [28]:
erro_gols_casa = mean_absolute_error( y_gc_test, previsoes[1]) # Erro medio dos gols de casa
print("MAE Gols Casa:", erro_gols_casa)

MAE Gols Casa: 0.8261170983314514

In [29]:
erro_gols_fora = mean_absolute_error(y_gf_test, previsoes[2]) #  Erro medio dos gols visitantes
print("MAE Gols Fora:", erro_gols_fora)

MAE Gols Fora: 0.6104728579521179

In [32]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 20)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 64)        │      1,344 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 64)        │          0 │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 32)        │      2,080 │ dropout_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ vitoria (Dense)     │ (None, 1)         │         33 │ dense_7[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gols_casa (Dense)   │ (None, 1)         │         33 │ dense_7[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gols_fora (Dense)   │ (None, 1)         │         33 │ dense_7[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 10,571 (41.30 KB)

 Trainable params: 3,523 (13.76 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 7,048 (27.54 KB)